repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      args: ["wagtailflags", "setup.py", "--line-length=79"]
      exclude: migrations
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.188
    hooks:
    - id: ruff
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["wagtailflags"]
