dist: xenial
language: python
cache: pip

matrix:
  include:
    - env: TOXENV=lint
      python: 3.6
    - env: TOXENV=py36-dj111-wag113
      python: 3.6
    - env: TOXENV=py36-dj111-wag23
      python: 3.6
    - env: TOXENV=py36-dj20-wag23
      python: 3.6
    - env: TOXENV=py36-dj22-wag23
      python: 3.6
    - env: TOXENV=py36-dj22-wag24
      python: 3.6
    - env: TOXENV=py36-dj22-wag24
      python: 3.7

install:
  pip install tox coveralls

script:
  tox

after_success:
  coveralls
