dist: xenial
language: python
cache: pip

matrix:
  include:
    - env: TOXENV=lint
      python: 3.6
    - env: TOXENV=py36-dj111-wag23
      python: 3.6
    - env: TOXENV=py36-dj22-wag23
      python: 3.6
    - env: TOXENV=py36-dj22-wag29
      python: 3.6
    - env: TOXENV=py38-dj22-wag29
      python: 3.8
    - env: TOXENV=py36-dj22-wag210
      python: 3.6
    - env: TOXENV=py38-dj22-wag210
      python: 3.8

install:
  pip install tox coveralls

script:
  tox

after_success:
  coveralls
