[tox]
skipsdist=True
envlist=
    lint,
    python3.13-django5.2-wagtail7.0
    python{3.13,3.14}-django{5.2,6.0}-wagtail7.4
    coverage

[testenv]
install_command=pip install -e ".[testing]" -U {opts} {packages}
commands=
    python -b -m coverage run --parallel-mode --source='wagtailflags' {envbindir}/django-admin test {posargs}
setenv=
    DJANGO_SETTINGS_MODULE=wagtailflags.tests.settings

basepython=
    python3.13: python3.13
    python3.14: python3.14

deps=
    django5.2: Django>=5.2,<5.3
    django6.0: Django>=6.0,<6.1
    wagtail7.0: wagtail>=7.0,<7.1
    wagtail7.4: wagtail>=7.4,<7.5

[testenv:lint]
basepython=python3.13
deps=
    ruff
    bandit
commands=
    ruff format --check
    ruff check wagtailflags
    bandit -c "pyproject.toml" -r wagtailflags

[testenv:coverage]
basepython=python3.13
deps=
    coverage
    diff_cover
commands=
    coverage combine
    coverage xml
    diff-cover coverage.xml --compare-branch=origin/main --fail-under=100

[testenv:interactive]
basepython=python3.13

deps=
    Django>=5.2,<5.3
    wagtail>=7.4,<7.5

commands_pre=
    {envbindir}/django-admin makemigrations
    {envbindir}/django-admin migrate
    {envbindir}/django-admin shell -c "from django.contrib.auth.models import User;(not User.objects.filter(username='admin').exists()) and User.objects.create_superuser('admin', 'super@example.com', 'changeme')"

commands=
    {posargs:{envbindir}/django-admin runserver 0.0.0.0:8000}

setenv=
    DJANGO_SETTINGS_MODULE=wagtailflags.tests.settings
    INTERACTIVE=1
