[tox]
skipsdist=True
envlist=
    lint,
    python{3.12,3.13}-django{5.2}-wagtail{6.3,6.4,7.0}
    coverage

[testenv]
install_command=pip install -e ".[testing]" -U {opts} {packages}
commands=
    python -b -m coverage run --parallel-mode --source='wagtailflags' {envbindir}/django-admin test {posargs}
setenv=
    DJANGO_SETTINGS_MODULE=wagtailflags.tests.settings

basepython=
    python3.12: python3.12
    python3.13: python3.13

deps=
    django5.2: Django>=5.2,<5.3
    wagtail6.3: wagtail>=6.3,<6.4
    wagtail6.4: wagtail>=6.4,<6.5
    wagtail7.0: wagtail>=7.0,<7.1

[testenv:lint]
basepython=python3.13
deps=
    ruff
    bandit
commands=
    ruff format --check
    ruff check wagtailflags
    bandit -c "pyproject.toml" -r wagtailflags

[testenv:coverage]
basepython=python3.13
deps=
    coverage
    diff_cover
commands=
    coverage combine
    coverage xml
    diff-cover coverage.xml --compare-branch=origin/main --fail-under=100

[testenv:interactive]
basepython=python3.13

deps=
    Django>=5.2,<5.3
    wagtail>=7.0,<7.1

commands_pre=
    {envbindir}/django-admin makemigrations
    {envbindir}/django-admin migrate
    {envbindir}/django-admin shell -c "from django.contrib.auth.models import User;(not User.objects.filter(username='admin').exists()) and User.objects.create_superuser('admin', 'super@example.com', 'changeme')"

commands=
    {posargs:{envbindir}/django-admin runserver 0.0.0.0:8000}

setenv=
    DJANGO_SETTINGS_MODULE=wagtailflags.tests.settings
    INTERACTIVE=1
