name: test

on: [pull_request, push]

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox -e lint
        run: tox
        env:
          TOXENV: lint

  test:
    name: unittests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toxenv:
          # Legacy versions
          - py38-dj32-wag215

          # Current and latest versions
          - py311-dj32-wag30
          - py311-dj40-wag30
          - py311-dj40-waglatest

        include:
          - toxenv: py38-dj32-wag215
            python-version: "3.8"
          - toxenv: py311-dj32-wag30
            python-version: "3.11"
          - toxenv: py311-dj40-wag30
            python-version: "3.11"
          - toxenv: py311-dj40-waglatest
            python-version: "3.11"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox coveralls

      - name: Run tox
        run: |
            tox
        env:
          TOXENV: ${{ matrix.toxenv }}

      - name: Store test coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: .coverage.*

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Retrieve test coverage
        uses: actions/download-artifact@v2
        with:
          name: coverage

      - name: Check coverage
        run: tox -e coverage
