name: test

on: [pull_request, push]

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
  
      - name: Run tox -e lint
        run: tox
        env: 
          TOXENV: lint

  test:
    name: unittests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toxenv:
            - py36-dj22-wag27
            - py36-dj22-wag210
            - py36-dj31-wag210
            - py38-dj22-wag27
            - py38-dj22-wag210
            - py38-dj31-wag210
        include:
          - toxenv: py36-dj22-wag27
            python-version: 3.6
          - toxenv: py36-dj22-wag210
            python-version: 3.6
          - toxenv: py36-dj31-wag210
            python-version: 3.6
          - toxenv: py38-dj22-wag27
            python-version: 3.8
          - toxenv: py38-dj22-wag210
            python-version: 3.8
          - toxenv: py38-dj31-wag210
            python-version: 3.8

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox coveralls

      - name: Run tox
        run: |
            tox
            coveralls
        env: 
          TOXENV: ${{ matrix.toxenv }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
