name: test

on: [pull_request, push]

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox -e lint
        run: tox
        env:
          TOXENV: lint

  test:
    name: unittests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ['3.12']
        django: ['4.2', '5.0']
        wagtail: ['6.0', '6.1']
        include:
          - python: '3.8'
            django: '4.2'
            wagtail: '6.0'
          - python: '3.8'
            django: '4.2'
            wagtail: '6.1'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox coveralls

      - name: Run tox
        run: tox
        env:
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}


      - name: Store test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python }}-${{ matrix.django }}-${{ matrix.wagtail }}
          path: .coverage.*

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Retrieve test coverage
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Check coverage
        run: tox -e coverage
