name: test

on: [pull_request, push]

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox -e lint
        run: tox
        env:
          TOXENV: lint

  test:
    name: unittests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toxenv:
            - py36-dj22-wag211
            - py36-dj22-waglatest
            - py39-dj22-wag211
            - py39-dj22-waglatest
            - py39-dj32-waglatest
        include:
          - toxenv: py36-dj22-wag211
            python-version: 3.6
          - toxenv: py36-dj22-waglatest
            python-version: 3.6
          - toxenv: py39-dj22-waglatest
            python-version: 3.9
          - toxenv: py39-dj22-wag211
            python-version: 3.9
          - toxenv: py39-dj22-waglatest
            python-version: 3.9
          - toxenv: py39-dj32-waglatest
            python-version: 3.9

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox coveralls

      - name: Run tox
        run: |
            tox
            coveralls
        env:
          TOXENV: ${{ matrix.toxenv }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
